// MOVIES

export const GET_MOVIES_LIST_SUCCESS = 'GET_MOVIES_LIST_SUCCESS';
export const GET_MOVIES_LIST_FAILURE = 'GET_MOVIES_LIST_FAILURE';

export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
export const GET_MOVIE_DETAIL_FAILURE = 'GET_MOVIE_DETAILS_FAILURE';

